

--DDL - mexe na estrutura
CREATE
ALTER
DROP --drop apaga a tabela em si

CREATE DATABASE AlunoAtos;
DROP DATABASE AlunoAtos;

CREATE TABLE ALUNOS
(
    ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    IDADE INTEGER
);

-- PRIMARY KEY - chave primária
-- NULL OR NOT NULL - campos nulo ou não nulo
-- IDENTITY - auto incremento

DROP TABLE ALUNOS; -- Exclui a tabela

ALTER TABLE ALUNOS
ADD RG VARCHAR (12);

ALTER TABLE ALUNOS
DROP COLUMN IDADE;

ALTER TABLE ALUNOS
ALTER COLUMN NOME VARCHAR (200) NOT NULL;


-------------------
CREATE TABLE CURSOS
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR (30) NOT NULL,
	CARGA_HORARIA INTEGER NOT NULL,
	ATIVO BIT DEFAULT 1,
	DESCRICAO TEXT
)

CREATE TABLE DISCIPLINAS
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR (30) NOT NULL,
	CARGA_HORARIA INTEGER NOT NULL,
	FK_CURSO INTEGER NOT NULL,
	FOREIGN KEY (FK_CURSO) REFERENCES CURSOS(ID)
)

CREATE TABLE MATRICULAS
(
    ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
    FK_ALUNO INTEGER NOT NULL,
    FK_CURSO INTEGER NOT NULL,
    FOREIGN KEY (FK_ALUNO) REFERENCES ALUNOS(ID),
    FOREIGN KEY(FK_CURSO) REFERENCES CURSOS(ID)
)

--DML
INSERT
UPDATE
DELETE
SELECT

--CRUD = CreateReadUpdateDelete

--INSERT
SELECT * FROM alunos --selecionar

INSERT INTO alunos
VALUES(1,'Fabrício', '12345678977',32);

INSERT INTO alunos (ID,NOME,CPF)
VALUES(2,'Murilo', '15555555544');

INSERT INTO alunos
VALUES(3,'Fabrício', '12345678977',32);
INSERT INTO alunos
VALUES(4,'Fabrício', '12345678977',32);
INSERT INTO alunos
VALUES(5,'Fabrício', '12345678977',32);

INSERT INTO alunos (ID,NOME,CPF)
VALUES(6,'Murilo', '15555555544');


--UPDATE - atualização

UPDATE ALUNOS
SET IDADE = 27 --necessário fazer filtragem com comando where para especificar e não mudar todo o banco de dados
WHERE ID = 2

UPDATE ALUNOS
SET IDADE = 22
WHERE NOME = 'Fabrício'

UPDATE ALUNOS
SET IDADE = 32, CPF = '22222222222'
WHERE ID = 5

UPDATE ALUNOS
SET CPF = '22222222222'
WHERE ID = 5 and IDADE > 25

UPDATE ALUNOS
SET NOME = NULL --na criação da tabela foi colocado "NOT NULL", então não é possível executar esse código
WHERE ID = 2

UPDATE ALUNOS
SET NOME = ''
WHERE ID = 2

UPDATE ALUNOS
SET IDADE = NULL
WHERE ID = 4

SELECT * FROM alunos 


--DELETE - Delete apaga as informações da tabela. E o drop apaga a tabela em si

DELETE FROM ALUNOS

DELETE FROM ALUNOS
WHERE ID = 11

DELETE FROM ALUNOS
WHERE IDADE IS NULL

DELETE FROM ALUNOS
WHERE IDADE IS NOT NULL

DELETE FROM ALUNOS
WHERE NOME = 'fabrício'

SELECT * FROM alunos
WHERE NOME != ''
ORDER BY NOME

SELECT * FROM alunos
WHERE NOME != ''
ORDER BY NOME ASC --(Ascendente)

SELECT * FROM alunos
WHERE NOME != ''
ORDER BY 2 DESC --coluna 2 (ID)




